import Faq from "./Faq";
import Image from "./ImageC";
import "../Style/WhyNeed.css"
export default function Whyneed(){
    return(
        <>
        <section className="whyneedcontainer">
            <div className="heading">
                <h2>Why we Need AIorNot</h2>
            </div>
            <div className="content">
                <div className="faqmain">
                    <Faq question={'Q1. What is the main purpose of an AI-or-Not website?'} answer={'A1: Its main purpose is to detect whether an image, video, or text is generated by AI or created by a human. This helps users know if content is real, edited, or fake.'}/>
                    <Faq question={'Q2. Why is detecting AI-generated content important?'} answer={'A2: AI-generated content can be used to spread misinformation, fake news, or deepfakes. Detecting it ensures trust, authenticity, and safety online.'}/>
                    <Faq question={'Q3. Who can benefit from using an AI-or-Not website?'} answer={'A3: Journalists and media professionals → to verify sources.Social media users ,to avoid sharing fake content.Businesses and educators , to ensure authenticity in materials.'}/>
                    <Faq question={'Q4. How does an AI-or-Not website help in security or trust?'} answer={'A4: By analyzing patterns, metadata, and AI artifacts, it prevents fraud, misinformation, and manipulated media, creating a safer online environment.'}/>
                    <Faq question={'Q5. Why do we need AI detection in the age of advanced AI tools?'} answer={'A5: As AI tools become more powerful, it becomes hard to visually distinguish AI content from real content. An AI-or-Not website provides a quick, reliable way to verify authenticity.'}/>
                </div>
                <div className="faq-imagesection">
                    <Image src={'/image/faq.avif'} transform ="perspective(500px) rotateY(0deg)" />
                </div>
            </div>
        </section>
        </>
    )
}